name: GoReleaser
run-name: GoReleaser ${{ startsWith(github.ref, 'refs/tags/v') && 'Release' || 'Snapshot' }}

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - v*

jobs:
  goreleaser:
    name: GoReleaser ${{ startsWith(github.ref, 'refs/tags/v') && 'Release' || 'Snapshot' }}
    # TODO: Switch to openchami once tagged
    uses: taylorludwig/openchami-github-actions/.github/workflows/go-build-release.yml@feature/go-build-release-tweaks
    # uses: OpenCHAMI/github-actions/.github/workflows/go-build-release.yml@v3.3
    with:
      fetch-depth: 1
      pre-build-commands: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      goreleaser-version: "~> v2"
      attestation-binary-path: "dist/pcs_linux_amd64_v3/power-control, dist/pcs_linux_arm64_v8.0/power-control"
      registry-name: ghcr.io/openchami/pcs
