name: Run CT Tests
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  run_ct_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        storage:
          - ETCD
          - POSTGRES
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Install docker compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose make
      - name: Run ct tests
        run: make ct
        env:
          STORAGE: ${{ matrix.storage }}
